/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema.empresaTransporte.view;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import sistema.empresaTransporte.controller.FinalizarController;

/**
 *
 * @author brasi
 */
public class FinalizarView extends javax.swing.JFrame {

    private final FinalizarController controller;

    /**
     * Creates new form Finalizar
     */
    public FinalizarView() {
        initComponents();
        controller = new FinalizarController(this);
        controller.exibeValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pay = new javax.swing.ButtonGroup();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButtonDinheiro = new javax.swing.JRadioButton();
        jRadioButtonCartão = new javax.swing.JRadioButton();
        jRadioButtonPix = new javax.swing.JRadioButton();
        jLabel12ValorFinal = new javax.swing.JLabel();
        jLabelDescontosTotais = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();
        jTextFieldCpf = new javax.swing.JTextField();
        jTextFieldSobrenome = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jButton1Finalizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel13.setText("- 5%");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 40, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel12.setText("+10%");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 40, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel11.setText("-10%");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 40, 30));

        pay.add(jRadioButtonDinheiro);
        jRadioButtonDinheiro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jRadioButtonDinheiro.setText("DINHEIRO");
        jRadioButtonDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDinheiroActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 100, -1));

        pay.add(jRadioButtonCartão);
        jRadioButtonCartão.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jRadioButtonCartão.setText("CARTÃO");
        jRadioButtonCartão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCartãoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonCartão, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        pay.add(jRadioButtonPix);
        jRadioButtonPix.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jRadioButtonPix.setText("PIX");
        jRadioButtonPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPixActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonPix, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        jLabel12ValorFinal.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12ValorFinal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12ValorFinal.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 255, 51)));
        getContentPane().add(jLabel12ValorFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 90, 40));

        jLabelDescontosTotais.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDescontosTotais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescontosTotais.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 255, 51)));
        getContentPane().add(jLabelDescontosTotais, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 90, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel10.setText("Descontos totais  R$");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 200, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel9.setText("Valor Final  R$");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 150, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel8.setText("Idade:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 100, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel7.setText("CPF:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 100, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel6.setText("Sobrenome:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel5.setText("Nome:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, 30));

        jTextFieldIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 220, 50));

        jTextFieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCpfActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 220, 50));

        jTextFieldSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSobrenomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 220, 50));

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 220, 50));

        jButton1Finalizar.setBackground(new java.awt.Color(153, 0, 153));
        jButton1Finalizar.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton1Finalizar.setForeground(new java.awt.Color(255, 255, 255));
        jButton1Finalizar.setText("FINALIZAR PAGAMENTO");
        jButton1Finalizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1FinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 330, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/empresaTransporte/view/imagens/icons/Logotipo menor.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(300, 500));
        jLabel3.setPreferredSize(new java.awt.Dimension(300, 300));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 240, 280));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/empresaTransporte/view/imagens/icons/Branco_Simples_Vertical_Seu_Story-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 310, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mateo\\AREADETRABALHO\\Projeto3\\src\\sistema\\empresaTransporte\\view\\imagens\\icons\\fundoFaixa1.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1FinalizarActionPerformed
        controller.salvaDados();
    }//GEN-LAST:event_jButton1FinalizarActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSobrenomeActionPerformed

    private void jTextFieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCpfActionPerformed

    private void jTextFieldIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdadeActionPerformed

    private void jRadioButtonPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPixActionPerformed
        controller.pagamentoView();
    }//GEN-LAST:event_jRadioButtonPixActionPerformed

    private void jRadioButtonCartãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCartãoActionPerformed
        controller.pagamentoView();
    }//GEN-LAST:event_jRadioButtonCartãoActionPerformed

    private void jRadioButtonDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDinheiroActionPerformed
        controller.pagamentoView();
    }//GEN-LAST:event_jRadioButtonDinheiroActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        TelaInicial telaInicial = new TelaInicial();
        telaInicial.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalizarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalizarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalizarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalizarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalizarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Finalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel12ValorFinal;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDescontosTotais;
    private javax.swing.JRadioButton jRadioButtonCartão;
    private javax.swing.JRadioButton jRadioButtonDinheiro;
    private javax.swing.JRadioButton jRadioButtonPix;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSobrenome;
    private javax.swing.ButtonGroup pay;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabel12ValorFinal() {
        return jLabel12ValorFinal;
    }

    public void setjLabel12ValorFinal(JLabel jLabel12ValorFinal) {
        this.jLabel12ValorFinal = jLabel12ValorFinal;
    }

    public JLabel getjLabelDescontosTotais() {
        return jLabelDescontosTotais;
    }

    public void setjLabelDescontosTotais(JLabel jLabelDescontosTotais) {
        this.jLabelDescontosTotais = jLabelDescontosTotais;
    }

    public JTextField getjTextFieldCpf() {
        return jTextFieldCpf;
    }

    public void setjTextFieldCpf(JTextField jTextFieldCpf) {
        this.jTextFieldCpf = jTextFieldCpf;
    }

    public JTextField getjTextFieldIdade() {
        return jTextFieldIdade;
    }

    public void setjTextFieldIdade(JTextField jTextFieldIdade) {
        this.jTextFieldIdade = jTextFieldIdade;
    }

    public JTextField getjTextFieldNome() {
        return jTextFieldNome;
    }

    public void setjTextFieldNome(JTextField jTextFieldNome) {
        this.jTextFieldNome = jTextFieldNome;
    }

    public JTextField getjTextFieldSobrenome() {
        return jTextFieldSobrenome;
    }

    public void setjTextFieldSobrenome(JTextField jTextFieldSobrenome) {
        this.jTextFieldSobrenome = jTextFieldSobrenome;
    }

    public JRadioButton getjRadioButtonCartão() {
        return jRadioButtonCartão;
    }

    public JRadioButton getjRadioButtonDinheiro() {
        return jRadioButtonDinheiro;
    }

    public JRadioButton getjRadioButtonPix() {
        return jRadioButtonPix;
    }

    public ButtonGroup getPay() {
        return pay;
    }

    public void setPay(ButtonGroup pay) {
        this.pay = pay;
    }

}
