/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema.empresaTransporte.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import sistema.empresaTransporte.controller.NovasRotasController;

/**
 *
 * @author brasi
 */
public class NovasRotas extends javax.swing.JFrame {
    private final NovasRotasController controller;
    /**
     * Creates new form NovasRotas
     */
    public NovasRotas() {
        initComponents();
        controller = new NovasRotasController(this);
        controller.exibeMotoristas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldData = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TextFieldDestinoUf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldOrigemUf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxMotorista = new javax.swing.JComboBox<>();
        jTextFieldValor = new javax.swing.JTextField();
        jTextFieldParadas = new javax.swing.JTextField();
        jTextFieldOrigemCity = new javax.swing.JTextField();
        TextFieldDestinoCity = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldData.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextFieldData.setText("00/00/0000");
        jTextFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 290, 50));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("                   Cidade");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 153)));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 250, -1));

        TextFieldDestinoUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDestinoUfActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldDestinoUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, 100, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" Estado/UF");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 153)));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, 100, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("                  Cidade");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 153)));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 250, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Estado/UF");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 153)));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 100, -1));

        jTextFieldOrigemUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrigemUfActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldOrigemUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 100, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Motorista");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor  R$");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Paradas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Destino");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Origem");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jComboBoxMotorista.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jComboBoxMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMotoristaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxMotorista, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 280, 50));

        jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 290, 50));

        jTextFieldParadas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        getContentPane().add(jTextFieldParadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 280, 50));
        getContentPane().add(jTextFieldOrigemCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 250, 50));

        TextFieldDestinoCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDestinoCityActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldDestinoCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 250, 50));

        jButtonSalvar.setBackground(new java.awt.Color(153, 0, 153));
        jButtonSalvar.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 270, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/empresaTransporte/view/imagens/icons/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 960, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/empresaTransporte/view/imagens/icons/onibusWall.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(860, 660));
        jLabel1.setMinimumSize(new java.awt.Dimension(860, 660));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        controller.salvarDados();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorActionPerformed

    private void TextFieldDestinoCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDestinoCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDestinoCityActionPerformed

    private void jComboBoxMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMotoristaActionPerformed

    private void jTextFieldOrigemUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrigemUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrigemUfActionPerformed

    private void TextFieldDestinoUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDestinoUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDestinoUfActionPerformed

    private void jTextFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MenuEmpresa menuEmpresa = new MenuEmpresa();
        menuEmpresa.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovasRotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovasRotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovasRotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovasRotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovasRotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldDestinoCity;
    private javax.swing.JTextField TextFieldDestinoUf;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxMotorista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldOrigemCity;
    private javax.swing.JTextField jTextFieldOrigemUf;
    private javax.swing.JTextField jTextFieldParadas;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getjComboBoxMotorista() {
        return jComboBoxMotorista;
    }

    public void setjComboBoxMotorista(JComboBox<String> jComboBoxMotorista) {
        this.jComboBoxMotorista = jComboBoxMotorista;
    }

    public JButton getjButtonSalvar() {
        return jButtonSalvar;
    }

    public void setjButtonSalvar(JButton jButtonSalvar) {
        this.jButtonSalvar = jButtonSalvar;
    }

    public JTextField getTextFieldDestinoCity() {
        return TextFieldDestinoCity;
    }

    public void setTextFieldDestinoCity(JTextField TextFieldDestinoCity) {
        this.TextFieldDestinoCity = TextFieldDestinoCity;
    }

    public JTextField getTextFieldDestinoUf() {
        return TextFieldDestinoUf;
    }

    public void setTextFieldDestinoUf(JTextField TextFieldDestinoUf) {
        this.TextFieldDestinoUf = TextFieldDestinoUf;
    }

    public JTextField getjTextFieldOrigemCity() {
        return jTextFieldOrigemCity;
    }

    public void setjTextFieldOrigemCity(JTextField jTextFieldOrigemCity) {
        this.jTextFieldOrigemCity = jTextFieldOrigemCity;
    }

    public JTextField getjTextFieldOrigemUf() {
        return jTextFieldOrigemUf;
    }

    public void setjTextFieldOrigemUf(JTextField jTextFieldOrigemUf) {
        this.jTextFieldOrigemUf = jTextFieldOrigemUf;
    }

    public JTextField getjTextFieldParadas() {
        return jTextFieldParadas;
    }

    public void setjTextFieldParadas(JTextField jTextFieldParadas) {
        this.jTextFieldParadas = jTextFieldParadas;
    }

    public JTextField getjTextFieldValor() {
        return jTextFieldValor;
    }

    public JTextField getjTextFieldData() {
        return jTextFieldData;
    }

    public void setjTextFieldData(JTextField jTextFieldData) {
        this.jTextFieldData = jTextFieldData;
    }
    
}
