/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema.empresaTransporte.view;

import sistema.empresaTransporte.codigos.models.meio.DAO.Banco;
import sistema.empresaTransporte.controller.TelaInicialController;

/**
 *
 * @author brasi
 */
public class TelaInicial extends javax.swing.JFrame {

    private final TelaInicialController controller;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        controller = new TelaInicialController(this);
        Banco.carregar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botãoFuncionarios = new javax.swing.JButton();
        botãoPassagem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(860, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/empresaTransporte/view/imagens/icons/Logotipo-removebg-preview - Copia.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(300, 500));
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 300));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 400, 410));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/empresaTransporte/view/imagens/icons/Branco_Simples_Vertical_Seu_Story-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        botãoFuncionarios.setBackground(new java.awt.Color(153, 0, 153));
        botãoFuncionarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botãoFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        botãoFuncionarios.setText("Para Funcionários");
        botãoFuncionarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botãoFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoFuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(botãoFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 290, 50));

        botãoPassagem.setBackground(new java.awt.Color(153, 0, 153));
        botãoPassagem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botãoPassagem.setForeground(new java.awt.Color(255, 255, 255));
        botãoPassagem.setText("Passagens Clique Aqui");
        botãoPassagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botãoPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoPassagemActionPerformed(evt);
            }
        });
        getContentPane().add(botãoPassagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 290, 50));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/empresaTransporte/view/imagens/icons/wp2120660222.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botãoFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoFuncionariosActionPerformed
        controller.irLogin();
    }//GEN-LAST:event_botãoFuncionariosActionPerformed

    private void botãoPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoPassagemActionPerformed
        controller.irOrigemDestino();
    }//GEN-LAST:event_botãoPassagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botãoFuncionarios;
    private javax.swing.JButton botãoPassagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
